type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  organization: Organization
}

type Organization @table {
  name: String!
  createdAt: Timestamp!
  contactEmail: String
}

type Project @table {
  organization: Organization!
  name: String!
  createdAt: Timestamp!
  description: String
  ownerUser: User
}

type AIService @table {
  name: String!
  provider: String!
  tokenCostPerUnit: Float!
  unitType: String!
  description: String
  apiUrl: String
}

type TokenUsage @table {
  project: Project!
  aiService: AIService!
  tokensUsed: Int!
  costInCents: Int!
  timestamp: Timestamp!
  requestDetails: String
  responseDetails: String
}

type Alert @table {
  user: User!
  project: Project!
  name: String!
  threshold: Int!
  unit: String!
  period: String!
  status: String!
  createdAt: Timestamp!
  description: String
  triggeredAt: Timestamp
}